name: mbsf_analytic_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.8
  - pip=22.2.2
  - ipykernel #TODO: validate
  - pandas=1.5.1
  - numpy=1.23.4
  - yaml=0.2.5
  - pyyaml=6.0
  - pip:
    - census
    - us
