name: census_acs5_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.8
  - census=0.8.20
  - yaml=0.2.5
  - pyyaml=6.0
  - pyarrow=11.0.0
  - pip=22.2.2
  - pip:
      - us==2.0.2
      - duckdb==0.8.1
      - pandas==1.5.1
      - numpy==1.23.4
      - ipykernel==6.23.3
